apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-k8s
spec:
  replicas: 8
  selector:
    matchLabels:
      app: lab
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: lab
    spec:
      volumes:
        - name: volume-k8s
          persistentVolumeClaim:
            claimName: pvc01-nfs
      containers:
        - name: ctr-k8s
          image: jeffersonrago/k8s-host
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/paramanha/"
              name: volume-k8s

---
apiVersion: v1
kind: Service
metadata:
  name: svc-k8s
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: lab
