version: '2.0'

services:
  db:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 4linux
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 4linux
  
  wordpress:
    image: wordpress
    depends_on:
      - db
    ports:
      - '8080:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 4linux

volumes:
    mysql-data:
